version: 0.0.0+{build}

skip_tags: true

skip_branch_with_pr: true

build:
  verbosity: minimal

test: false

environment:
  WHISKEY_DISABLE_ERROR_FORMAT: True
  matrix:
#   TODO: add back to build once Prism *and* Whiskey support PackageManagement 1.4.8.1.
#   - job_name: PowerShell 7.2 on Windows
#     job_group: pwsh
#     appveyor_build_worker_image: Visual Studio 2022  # Windows Server 2019

  - job_name: PowerShell 7.1 on macOS
    job_group: pwsh
    appveyor_build_worker_image: macOS

  - job_name: Windows PowerShell 5.1/.NET 4.6.2
    job_group: ps
    appveyor_build_worker_image: Visual Studio 2013  # Windows Server 2012R2

  - job_name: Windows PowerShell 5.1/.NET 4.8
    job_group: ps
    appveyor_build_worker_image: Visual Studio 2019  # Windows Server 2019

  - job_name: PowerShell 6.2 on Windows
    job_group: pwsh
    appveyor_build_worker_image: Visual Studio 2015  # Windows Server 2012R2

# TODO: figure out why builds hang on this platform
#  - job_name: PowerShell 7.2 on Ubuntu
#    job_group: pwsh
#    appveyor_build_worker_image: Ubuntu

  - job_name: PowerShell 7.1 on Windows
    job_group: pwsh
    appveyor_build_worker_image: Visual Studio 2019  # Windows Server 2019


artifacts:
- path: .output\*


for:
# Build in Windows PowerShell
- matrix:
    only:
    - job_group: ps
  build_script:
  - ps: |
        .\Scripts\init.ps1 -ErrorAction Stop
        Uninstall-Module -Name 'Prism'
        .\build.ps1

# Build in PowerShell
- matrix:
    only:
    - job_group: pwsh
  build_script:
  - pwsh: |
        ./Scripts/init.ps1 -ErrorAction Stop
        Uninstall-Module -Name 'Prism'
        ./build.ps1
